In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
import sqlalchemy
from sqlalchemy import create_engine

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [4]:
import sqlalchemy
from sqlalchemy import create_engine
import pandas as pd
import psycopg2

In [5]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [6]:
postgres_str = "postgresql://postgres:blitzkrieg@localhost:5432/gainesvillecrime";

In [7]:
# Create the connection
cnx = create_engine(postgres_str)

In [29]:
df_y = pd.read_sql_query('''select moonphase, 


case when cfs_type = 'Alcohol' then 1
when cfs_type = 'Assault' then 2
 when cfs_type = 'Battery' then 3
 when cfs_type = 'Death Inv/Homicide' then '4'
 when cfs_type = 'Drugs' then '5'
 when cfs_type = 'Fraud' then '6'
 when cfs_type = 'Gov Reg Vio' then '7'
 when cfs_type = 'Other' then '8'
 when cfs_type = 'Quality of Life' then '9'
 when cfs_type = 'Suicide' then '10'
 when cfs_type = 'Theft' then '11'
else 0
end,

count(c. cfs) as cnt_cfs
from callsforservice c
join classification cls
on c.cfs = cls.cfs
left join moonphase mp
on c. offensedate = mp.date
group by moonphase, cls.cfs_type
;''', cnx)




In [30]:
df_y

moonphase  case  cnt_cfs
0   Third Quarter     6      572
1   First Quarter     6      691
2       Full Moon     8     1206
3   First Quarter    11     4696
4   Third Quarter    10        1
5   First Quarter     1       88
6   Third Quarter     9     2170
7   Third Quarter     2      205
8   Third Quarter     1       75
9   Third Quarter     8     1131
10       New Moon     4      155
11  First Quarter     4      155
12       New Moon     8     1244
13      Full Moon     5      496
14  Third Quarter    11     4055
15  First Quarter     5      483
16      Full Moon     1       96
17       New Moon     9     2425
18      Full Moon     7      276
19       New Moon     6      653
20  Third Quarter     5      451
21       New Moon     3     1424
22       New Moon     7      301
23       New Moon     2      249
24  Third Quarter     3     1238
25  Third Quarter     4      145
26  First Quarter     9     2478
27  First Quarter     8     1290
28      Full Moon     6      668
29  Third Quarter     7      276
30  First Quarter     7      328
31      Full Moon    11     4235
32       New Moon     5      445
33       New Moon     1       94
34      Full Moon     4      148
35  First Quarter     2      243
36  First Quarter     3     1429
37      Full Moon     3     1439
38       New Moon    11     4549
39      Full Moon     9     2348
40      Full Moon     2      222

In [31]:
df_x = pd.read_sql_query('''Select moonphase

from callsforservice c
join classification cls
on c.cfs = cls.cfs
left join moonPhase mp
on c.offensedate = mp.date
;''', cnx)



In [32]:
df_x

moonphase
0          Full Moon
1          Full Moon
2      Third Quarter
3          Full Moon
4      Third Quarter
...              ...
44868  First Quarter
44869       New Moon
44870  Third Quarter
44871  Third Quarter
44872  Third Quarter

[44873 rows x 1 columns]

In [33]:
# Encode Categorical Columns
categ = ['moonphase']
le = LabelEncoder()
df_y[categ] = df_y[categ].apply(le.fit_transform)



In [57]:
df_y.head()

moonphase  case  cnt_cfs
0          3     6      572
1          0     6      691
2          1     8     1206
3          0    11     4696
4          3    10        1

In [81]:
y = df_y['moonphase']

X = df_y[['cnt_cfs','case']]

In [82]:
y.value_counts()

3    11
0    10
1    10
2    10
Name: moonphase, dtype: int64

In [83]:
X.describe()

cnt_cfs       case
count    41.000000  41.000000
mean   1094.463415   5.707317
std    1295.348063   3.116439
min       1.000000   1.000000
25%     222.000000   3.000000
50%     496.000000   6.000000
75%    1424.000000   8.000000
max    4696.000000  11.000000

In [84]:
X.shape

(41, 2)

In [85]:
y.shape

(41,)

In [86]:
# You can modify test_size to account for 30% testing/70% training
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3)

In [87]:
# Resample the training data with the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

In [88]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [89]:
y_pred = clf.predict(X_test)

In [90]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.21621621621621623


In [91]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1 2 0 6]
 [2 1 0 6]
 [1 2 0 7]
 [1 2 0 6]]


In [92]:
# Print the  classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.20      0.11      0.14         9
           1       0.14      0.11      0.12         9
           2       0.00      0.00      0.00        10
           3       0.24      0.67      0.35         9

    accuracy                           0.22        37
   macro avg       0.15      0.22      0.16        37
weighted avg       0.14      0.22      0.15        37



In [80]:
# MODULE DIRECTIONS FOR CONFUSION MATRIX

# Display the confusion matrix
#cm = confusion_matrix(y_test, y_pred)
#cm_df = pd.DataFrame(
    #cm, index=["Actual high_risk", "Actual low_risk"], columns=["Predicted high_risk", "Predicted low_risk"])
#cm_df