In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
import sqlalchemy
from sqlalchemy import create_engine

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
import sqlalchemy
from sqlalchemy import create_engine
import pandas as pd
import psycopg2

In [5]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [6]:
postgres_str = "postgresql://postgres:blitzkrieg@localhost:5432/gainesvillecrime";

In [7]:
# Create the connection
cnx = create_engine(postgres_str)

In [8]:
df_y = pd.read_sql_query('''Select cls.cfs_type 

from callsforservice c
join classification cls
on c.cfs = cls.cfs
left join moonPhase mp
on c.offensedate = mp.date
;''', cnx)




In [9]:
df_y

cfs_type
0              Battery
1              Battery
2      Quality of Life
3              Battery
4      Quality of Life
...                ...
44868          Battery
44869          Battery
44870            Other
44871            Drugs
44872          Battery

[44873 rows x 1 columns]

In [10]:
df_x = pd.read_sql_query('''Select offensedate, offensedow, offensehour,moonphase

from callsforservice c
join classification cls
on c.cfs = cls.cfs
left join moonPhase mp
on c.offensedate = mp.date
;''', cnx)



In [11]:
df_x

offensedate offensedow  offensehour      moonphase
0      2021-07-04     Sunday           21      Full Moon
1      2021-07-03   Saturday           22      Full Moon
2      2021-06-29    Tuesday           11  Third Quarter
3      2021-07-04     Sunday            4      Full Moon
4      2021-07-01   Thursday           13  Third Quarter
...           ...        ...          ...            ...
44868  2021-06-22    Tuesday           12  First Quarter
44869  2021-06-14     Monday           18       New Moon
44870  2021-06-26   Saturday            8  Third Quarter
44871  2021-06-26   Saturday           22  Third Quarter
44872  2021-06-26   Saturday            5  Third Quarter

[44873 rows x 4 columns]

In [12]:
# Encode Categorical Columns
categ = ['offensedate', 'offensedow', 'offensehour', 'moonphase']
le = LabelEncoder()
df_x[categ] = df_x[categ].apply(le.fit_transform)

In [13]:
# Merge dummy columns into main dataframe and drop originals 
le = LabelEncoder()
#df_xfit = le.fit_transform(df_x['moonphase'])



In [14]:
df_x

offensedate  offensedow  offensehour  moonphase
0             1280           3           21          1
1             1279           2           22          1
2             1275           5           11          3
3             1280           3            4          1
4             1277           4           13          3
...            ...         ...          ...        ...
44868         1268           5           12          0
44869         1260           1           18          2
44870         1272           2            8          3
44871         1272           2           22          3
44872         1272           2            5          3

[44873 rows x 4 columns]

In [15]:
y = df_y


X = df_x

In [16]:
y.value_counts()

cfs_type          
Theft                 17535
Quality of Life        9421
Battery                5530
Other                  4871
Fraud                  2584
Drugs                  1875
Gov Reg Vio            1181
Assault                 919
Death Inv/Homicide      603
Alcohol                 353
Suicide                   1
dtype: int64

In [17]:
X.describe()

offensedate    offensedow   offensehour     moonphase
count  44873.000000  44873.000000  44873.000000  44873.000000
mean     666.647739      2.978539     11.620262      1.452299
std      414.671943      2.021459      7.473682      1.112300
min        0.000000      0.000000      0.000000      0.000000
25%      296.000000      1.000000      5.000000      0.000000
50%      645.000000      3.000000     13.000000      1.000000
75%     1011.000000      5.000000     18.000000      2.000000
max     1456.000000      6.000000     23.000000      3.000000

In [18]:
X.shape

(44873, 4)

In [19]:
y.shape

(44873, 1)

In [28]:
# You can modify test_size to account for 30% testing/70% training
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3)

In [29]:
# Resample the training data with the RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

In [30]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [31]:
y_pred = clf.predict(X_test)

In [32]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.2819046204130144


In [33]:
#Confusion Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[   2    2   21    2    4    6    3    9   10   43]
 [   3    5   36    4    6    2    9   23   65  128]
 [  10   24  244    7   49   46   27  169  356  725]
 [   1    4   19    2    9    6    1   20   33   90]
 [   3    8   63    4   40   29   12   57  116  264]
 [   3    8   53   10   16   78    8   52  150  383]
 [   4    2   43    2   17   15    4   31   61  170]
 [  10   24  176   11   37   48   18  139  320  664]
 [  13   47  320   22   96  120   35  266  609 1338]
 [  31   61  518   38  121  239   82  379 1077 2672]]


In [34]:
# Print the  classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

                    precision    recall  f1-score   support

           Alcohol       0.03      0.02      0.02       102
           Assault       0.03      0.02      0.02       281
           Battery       0.16      0.15      0.15      1657
Death Inv/Homicide       0.02      0.01      0.01       185
             Drugs       0.10      0.07      0.08       596
             Fraud       0.13      0.10      0.12       761
       Gov Reg Vio       0.02      0.01      0.01       349
             Other       0.12      0.10      0.11      1447
   Quality of Life       0.22      0.21      0.22      2866
             Theft       0.41      0.51      0.46      5218

          accuracy                           0.28     13462
         macro avg       0.12      0.12      0.12     13462
      weighted avg       0.25      0.28      0.26     13462



In [27]:
# MODULE DIRECTIONS FOR CONFUSION MATRIX

# Display the confusion matrix
#cm = confusion_matrix(y_test, y_pred)
#cm_df = pd.DataFrame(
    #cm, index=["Actual high_risk", "Actual low_risk"], columns=["Predicted high_risk", "Predicted low_risk"])
#cm_df